### ISSUE TITLE
BOM & other infos

### ISSUE THREAD

**Issue by atroger** [Dolu1990/pmod_usb_host_x4#1]
Hi,

Do you (still) have the BOM for the board?
Could you make it available?

Regards.
(Great work btw!)

**Comment by Dolu1990** [comment]
Hi,

There it is, note that the quantities are all over the place ^^

[bom.xls](https://github.com/Dolu1990/pmod_usb_host_x4/files/8014516/bom.xls)

Also, for the 5V you need to connect it via a cable to the board.

Regards
Charles

**Comment by atroger** [comment]
Thank you Charles!

**Comment by atroger** [comment]
> Hi,
> 
> There it is, note that the quantities are all over the place ^^
> 
> [bom.xls](https://github.com/Dolu1990/pmod_usb_host_x4/files/8014516/bom.xls)
> 
> Also, for the 5V you need to connect it via a cable to the board.
> 
> Regards Charles

**Comment by atroger** [comment]
Hi Charles,

I'm a bit confused about one thing: Have you used 47uF or 150uF capacitors for C2 to C5? 6.3V or 10V?
(I guess 150uF 6.3V, according to the schematic, but I just want to be sure :)
6.3V seems a bit short for 5V though)

**Comment by Dolu1990** [comment]
hmm, i don't have anything to mesure what is actualy mounted, but i would say go for the 47 uf 10V.

As 150uF x4 is realy quite a lot.
